first draft TS-SDK general introduction for docs site
input-output-hk/marlowe-doc pull request #177
Opened 2023-10-18 19:14 UTC by joseph-fajen

Please review for completeness and accuracy. This is a first draft.

2023-10-19 06:07 UTC, sfoo-iohk commented on docs/developer-tools/ts-sdk-intro.md
> +To use the capabilities of the Marlowe TS-SDK, have an active link to a Marlowe Runtime instance and a browser-installed wallet extension that's compatible.
What does an "active link" to a Marlowe Runtime instance mean?

2023-10-19 06:13 UTC, olgahryniuk commented on docs/developer-tools/ts-sdk-intro.md
> +4. **Proof-of-Concept (PoC) templates**: Embark on your DApp journey using the TS-SDK's distilled example templates. These PoC templates serve as invaluable launching pads for your customized applica
```suggestion
4. **Proof-of-concept (PoC) templates**: Embark on your DApp journey using the TS-SDK's distilled example templates. These PoC templates serve as invaluable launching pads for your customized applications.
```

2023-10-19 06:14 UTC, olgahryniuk commented on docs/developer-tools/ts-sdk-intro.md
> +To use the capabilities of the Marlowe TS-SDK, have an active link to a Marlowe Runtime instance and a browser-installed wallet extension that's compatible.
```suggestion
To use the capabilities of the Marlowe TS-SDK, have an active link to a Marlowe Runtime instance and a compatible browser-installed wallet extension.
```

2023-10-19 06:16 UTC, olgahryniuk commented on docs/developer-tools/ts-sdk-intro.md
> +- **[Marlowe Payouts](https://github.com/input-output-hk/marlowe-payouts)**
I'd suggest not to capitalize 'Payouts' as we discussed before. Please see how these DApps are referenced throughout all the docs - for consistency. Might be worth adding them to the IOG style guide.

2023-10-19 06:17 UTC, olgahryniuk commented on docs/developer-tools/ts-sdk-intro.md
> +- **[Vesting Prototype](https://github.com/input-output-hk/marlowe-ts-sdk/blob/main/pocs/contract-example/vesting-flow.html)**
Is the vesting prototype different from the vesting DApp? If it' the same thing, suggest using 'DApp' for consistency with other examples.

2023-10-19 06:18 UTC, olgahryniuk commented on docs/developer-tools/ts-sdk-intro.md
> +Dive into the **[Vesting DApp](https://github.com/input-output-hk/marlowe-vesting)**, tailored for:
Same question about the capitalization of 'vesting'.

2023-10-19 06:25 UTC, olgahryniuk commented on docs/developer-tools/ts-sdk-intro.md
> +  - Tokenomics orchestration.
No need for full stops in a short bullet list, please. Only in the last bullet point.

2023-10-19 10:40 UTC, nhenin requested changes

2023-10-19 10:40 UTC, nhenin commented on docs/developer-tools/ts-sdk-intro.md
> +To use the capabilities of the Marlowe TS-SDK, have an active link to a Marlowe Runtime instance and a browser-installed wallet extension that's compatible.
I don't know what it is also... We should have a "How To Get this Active Link"

2023-10-19 10:40 UTC, nhenin commented on docs/developer-tools/ts-sdk-intro.md
> +- **[Vesting Prototype](https://github.com/input-output-hk/marlowe-ts-sdk/blob/main/pocs/contract-example/vesting-flow.html)**
I'm saying prototype in the code source... It is more a Prototype than a DApp... We are overselling here imo...

2023-10-19 10:40 UTC, nhenin commented on docs/developer-tools/ts-sdk-intro.md
> +- **[Vesting Prototype](https://github.com/input-output-hk/marlowe-ts-sdk/blob/main/pocs/contract-example/vesting-flow.html)**
The goal of these prototypes is not to provide services to end users (like a DApp is) over Marlowe technology but to show concrete examples on how to use the technology and which kind of use cases we can enable...

2023-10-19 18:12 UTC, joseph-fajen commented on docs/developer-tools/ts-sdk-intro.md
> +To use the capabilities of the Marlowe TS-SDK, have an active link to a Marlowe Runtime instance and a browser-installed wallet extension that's compatible.
I'm just referring to a URL that points to a running instance of the Runtime. I'll make this more clear.

2023-10-19 19:22 UTC, joseph-fajen commented on docs/developer-tools/ts-sdk-intro.md
> +### User narratives
Thanks for the feedback. I wanted to include this initially to find out how relevant it may be for this intro page. I've removed them.

2023-10-19 19:23 UTC, joseph-fajen commented on docs/developer-tools/ts-sdk-intro.md
> +4. **Proof-of-Concept (PoC) templates**: Embark on your DApp journey using the TS-SDK's distilled example templates. These PoC templates serve as invaluable launching pads for your customized applica
Thanks Olga. I've combed through to make sure I'm using the initial cap practice of the IOG style guide.

2023-10-19 20:36 UTC, joseph-fajen commented on docs/developer-tools/ts-sdk-intro.md
> +- **[Vesting Prototype](https://github.com/input-output-hk/marlowe-ts-sdk/blob/main/pocs/contract-example/vesting-flow.html)**
I've clarified how these are described. I think the revised draft is more clear.

2023-10-20 15:05 UTC, nhenin approved these changes

2023-10-20 16:07 UTC, merged