Add compatibility matrix
input-output-hk/marlowe-doc pull request #187
Opened 2023-11-17 15:20 UTC by sfoo-iohk

This page can be used for release tracking and eventually version skew policies as well as EOL support.

2023-11-17 19:51 UTC, joseph-fajen commented on docs/platform-and-architecture/versioning-policy.md
> +At the moment, Marlowe does not strictly adhere to [Semantic Versioning](https://semver.org/). Prior to a `v1` release, changes may be breaking and backporting future fixes is to be determined.
To make the link more obvious, please make it bold.

2023-11-17 19:52 UTC, joseph-fajen commented on docs/platform-and-architecture/versioning-policy.md
> +Releases are not operating at a regular cadence yet although critical bug fixes will typically lead to faster releases.
Please add a comma after "yet"

2023-11-17 20:01 UTC, joseph-fajen requested changes
Could you make one or two statements that make the practical impact of this matrix more explicit and abundantly clear? It may be expected to be evident to the intended audience. But speaking for myself, I'm not sure what I should do with this info if I want to use Marlowe. Please clarify the purpose of this page and why it is needed.

2023-11-17 20:52 UTC, sfoo-iohk commented on docs/platform-and-architecture/versioning-policy.md
> +:::
fyi, this is Marlowe parity of https://docs.cardano.org/tools/comp-matrix/

If a user abstracted away these pieces through Demeter, etc, this document is not relevant to them

2023-11-17 21:08 UTC, joseph-fajen approved these changes

2023-11-20 17:29 UTC, bwbush commented on docs/platform-and-architecture/versioning-policy.md
> +| `marlowe-cli-0.0.11.0` | ✓ | ✓ | ✓ | ? |
We verified that the old versions don't work with the new node:
```suggestion
| `marlowe-cli-0.0.12.0` | ✓ | ✓ | ✓ | ✗ |
| `marlowe-cli-0.0.11.0` | ✓ | ✓ | ✓ | ✗ |
```

2023-11-20 17:29 UTC, bwbush approved these changes

2023-11-20 21:09 UTC, merged